spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lite_chat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong&allowMultiQueries=true
    username: root
    password: wyh246859
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: localhost
    password: wyh246859
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8081